name: Rodar testes unitários

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Listar estrutura do projeto
        run: find . -name "*.csproj" | head -20

      - name: Restaurar dependências da API
        run: dotnet restore AutoManager.API.csproj

      - name: Build da API
        run: dotnet build AutoManager.API.csproj --no-restore --configuration Release
